version: "3"

services:
  web:
    build: .
    command: python /ch4-bookstore/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/ch4-bookstore
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - 'DJANGO_SECRET_KEY=django-insecure-#r&yude!v4gi+2)2_f4t!*hd0p^_kci#(oo(nfqup8dpaf_mb*'
      - 'DJANGO_DEBUG=True'
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: