# Generated by Django 4.0.8 on 2022-12-22 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_id_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name = 'price',
        ),
    ]
